# Generated by Django 3.2 on 2021-10-24 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=50)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Voluntary'), (2, 'Paid')])),
                ('qualification', models.PositiveSmallIntegerField(choices=[(1, 'Masters Degree'), (2, 'Bachelor Degree'), (3, 'National Diploma'), (4, 'High School')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('vpp', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='vppsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=32, null=True)),
                ('walletid', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vppsub',
                'verbose_name_plural': 'vppsubs',
            },
        ),
        migrations.CreateModel(
            name='Vpp_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='members/idcard')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='members/idcard')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='members/selfie')),
                ('id_number', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Vpp_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vpp_verified',
                'verbose_name_plural': 'Vpps_verified',
            },
        ),
        migrations.CreateModel(
            name='Vpp_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('acct_number', models.CharField(blank=True, max_length=32, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Vpp_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vpp_bank',
                'verbose_name_plural': 'Vpps_bank',
            },
        ),
        migrations.CreateModel(
            name='vpp_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vpp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, default='Newyork', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Vpp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vpp',
                'verbose_name_plural': 'Vpps',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='members/profiles/avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Agent_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='members/fidcard')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='members/bidcard')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='members/selfie')),
                ('qualification', models.ImageField(blank=True, null=True, upload_to='members/certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Agent_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent_verified',
                'verbose_name_plural': 'Agents_verified',
            },
        ),
    ]
